alias artisan="php artisan"
[[ -f `which bat` ]] && alias cat=bat 
[[ -f `which batcat` ]] && alias cat=batcat
alias copy=clipcopy
alias drun='docker run -ti --rm -v $PWD:/app -w /app'
alias d="docker-compose"
alias dx="docker-compose exec"
alias dup="docker-compose up -d"
alias du="ncdu --color off"
alias icat="kitty +kitten icat"
alias mocp="mocp -T green_theme"
alias o='xdg-open &>/dev/null'
alias open='xdg-open &>/dev/null'
alias rm="trash"
alias p="sudo pacman"
alias paru="paru --removemake --sudoloop --bottomup --skipreview"
alias s="pacman -Ss"
alias sail="./vendor/bin/sail"
alias sd="sudo systemctl"
alias saul=sail
alias serve="php artisan serve --host 0.0.0.0 &>/dev/null"
alias si="sudo pacman -S"
alias sudo="sudo "
alias tinker="docker-compose exec app php artisan tinker"

# directories
alias lsa="exa -lagH --group-directories-first --icons"
alias l="exa -lagH --group-directories-first --icons"
alias ll="exa -lgH --group-directories-first --icons"
alias la="exa -lAgH --group-directories-first --icons"
alias ldir="exa -lgDH --git --icons"
