# QOL
set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g status-interval 1
set -g history-limit 100000
set -g renumber-windows on
set -g set-clipboard on

# Window status format
set -g window-status-format "#I:#W#F"
set -g window-status-current-format "#I:#W#F"
set -g window-status-separator ' '

# Automatic renaming based on current directory
setw -g automatic-rename on
setw -g automatic-rename-format '#{b:pane_current_path}'

# Automatic session renaming based on current directory (respects manual renames)
set-hook -g pane-focus-in 'run-shell "~/.config/tmux/session_rename_flag.sh"'

# Update window name on pane focus
# set-hook -g pane-focus-in 'run-shell "tmux rename-window \"$(basename \"#{pane_current_path}\")\""'