# QOL
set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g status-interval 1
set -g history-limit 100000
set -g renumber-windows on

# Status line configuration
set -g status-position top
set -g status on
set -g status-style "bg=#{?client_prefix,#{?pane_mode,yellow,#ffff00},#{?pane_mode,#5fd7af,#282c34}},fg=#{?client_prefix,black,#{?pane_mode,#000000,#abb2bf}}"
set -g status-left "#[fg=#{?client_prefix,black,#{?pane_mode,#000000,#61afef}},bg=#{?client_prefix,#{?pane_mode,yellow,#ffff00},#{?pane_mode,#5fd7af,#282c34}},bold]#S #[fg=#{?client_prefix,black,#{?pane_mode,#000000,#5c6370}}]│"
set -g status-right "#[fg=green]#(basename "#{pane_current_path}") #[fg=yellow]#(free | awk '/^Mem/ { printf("%.0f%%", $3/$2 * 100) }' </proc/meminfo) #[fg=red]#(date "+%H:%M")"
# set -g status-justify left

# Window status format
set -g window-status-format "#I:#W#F"
set -g window-status-current-format "#I:#W#F"
set -g window-status-separator ' '

# Automatic renaming based on current directory
setw -g automatic-rename on
setw -g automatic-rename-format '#{b:pane_current_path}'

# Automatic session renaming based on current directory
set-hook -g pane-focus-in 'run-shell "tmux rename-session \"$(basename \"#{pane_current_path}\")\""'

# Update window name on pane focus
# set-hook -g pane-focus-in 'run-shell "tmux rename-window \"$(basename \"#{pane_current_path}\")\""'