set -g @continuum-restore 'on'
set-option -g @plugin 'b0o/tmux-autoreload'

# Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'niqodea/tmux-matryoshka'
set -g @plugin 'binoymanoj/tmux-minimal-theme'

# TPM shortcuts
# prefix + I – install plugins
# prefix + U – update plugins
# prefix + Alt + u – clean unused plugins