source-file ~/.config/tmux/core.conf
source-file ~/.config/tmux/ui.conf
source-file ~/.config/tmux/behavior.conf
source-file ~/.config/tmux/keys.conf
source-file ~/.config/tmux/plugins.conf
run '~/.config/tmux/plugins/tpm/tpm'

set -g status-position top