alias artisan="php artisan"
[[ -f `which bat` ]] && alias cat=bat 
[[ -f `which batcat` ]] && alias cat=batcat
alias copy=clipcopy
alias d="docker-compose"
alias dx="docker-compose exec"
alias dup="docker-compose up -d"
alias du=dust
alias icat="kitty +kitten icat"
alias mocp="mocp -T green_theme"
alias o='xdg-open &>/dev/null'
alias open='xdg-open &>/dev/null'
alias rm="trash -i"
alias p="sudo pacman"
alias paru="paru --removemake --sudoloop --bottomup --skipreview"
alias s="pacman -Ss"
alias sail="./vendor/bin/sail"
alias serve="php artisan serve --host 0.0.0.0 &>/dev/null"
alias si="sudo pacman -S"
alias sudo="sudo "
