alias artisan="php artisan"
alias cat=bat
alias copy=clipcopy
alias ctf="cd ~/dev/cyber-sec/CTF"
alias du=dust
alias ldir="ll -d */"
alias mocp="mocp -T green_theme"
alias open='xdg-open &>/dev/null'
alias rm="trash -i"
alias p="sudo pacman"
alias s="pacman -Ss"
alias serve="php artisan serve &>/dev/null"
alias si="sudo pacman -S"
alias sudo="sudo "
